/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package catchthebeat.ui;

import catchthebeat.GameCreator;
import javax.swing.JTextField;

/**
 * Class PlayersDialog
 * 
 * This JDialog provides tools for users to view and change players names.
 * 
 * 1) Number of players is limited to 10
 * 2) Edits are validated and saved by GameCreator
 * 3) If user leaves blank one ore more fields these will be replaced by 
 *    default name e.g. Player 7 
 * 
 * @author Roman Velic
 * @version 2012.04
 */
public class PlayersDialog extends javax.swing.JDialog {

    private GameCreator gameCreator;
    
    /** Creates new form PlayersDialog */
    public PlayersDialog(java.awt.Frame parent, boolean modal, GameCreator gmc, String[] players) {
        super(parent, modal);
        initComponents();
        JTextField[] pfields = {p1Field, p2Field, p3Field, p4Field, p5Field,
                                p6Field, p7Field, p8Field, p9Field, p10Field};
        
        // set players names for each field
        for (int playerNo = 0; playerNo < players.length && playerNo < pfields.length; playerNo++) {
            pfields[playerNo].setText(players[playerNo]);
        }
        gameCreator = gmc;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        playersPanel = new javax.swing.JPanel();
        p1Label = new javax.swing.JLabel();
        p1Field = new javax.swing.JTextField();
        p2Label = new javax.swing.JLabel();
        p2Field = new javax.swing.JTextField();
        p3Label = new javax.swing.JLabel();
        p3Field = new javax.swing.JTextField();
        p4Label = new javax.swing.JLabel();
        p4Field = new javax.swing.JTextField();
        p5Label = new javax.swing.JLabel();
        p5Field = new javax.swing.JTextField();
        p6Label = new javax.swing.JLabel();
        p6Field = new javax.swing.JTextField();
        p7Label = new javax.swing.JLabel();
        p7Field = new javax.swing.JTextField();
        p8Label = new javax.swing.JLabel();
        p8Field = new javax.swing.JTextField();
        p9Label = new javax.swing.JLabel();
        p9Field = new javax.swing.JTextField();
        p10Label = new javax.swing.JLabel();
        p10Field = new javax.swing.JTextField();
        controlsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Players");
        setLocationByPlatform(true);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(390, 400));

        playersPanel.setLayout(new java.awt.GridBagLayout());

        p1Label.setText("1.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p1Label, gridBagConstraints);

        p1Field.setText("Player 1");
        p1Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p1Field, gridBagConstraints);

        p2Label.setText("2.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p2Label, gridBagConstraints);

        p2Field.setText("Player 2");
        p2Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p2Field, gridBagConstraints);

        p3Label.setText("3.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p3Label, gridBagConstraints);

        p3Field.setText("Player 3");
        p3Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p3Field, gridBagConstraints);

        p4Label.setText("4.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p4Label, gridBagConstraints);

        p4Field.setText("Player 4");
        p4Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p4Field, gridBagConstraints);

        p5Label.setText("5.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p5Label, gridBagConstraints);

        p5Field.setText("Player 5");
        p5Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p5Field, gridBagConstraints);

        p6Label.setText("6.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p6Label, gridBagConstraints);

        p6Field.setText("Player 6");
        p6Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p6Field, gridBagConstraints);

        p7Label.setText("7.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p7Label, gridBagConstraints);

        p7Field.setText("Player 7");
        p7Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p7Field, gridBagConstraints);

        p8Label.setText("8.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p8Label, gridBagConstraints);

        p8Field.setText("Player 8");
        p8Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p8Field, gridBagConstraints);

        p9Label.setText("9.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p9Label, gridBagConstraints);

        p9Field.setText("Player 9");
        p9Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p9Field, gridBagConstraints);

        p10Label.setText("10.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p10Label, gridBagConstraints);

        p10Field.setText("Player 10");
        p10Field.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        playersPanel.add(p10Field, gridBagConstraints);

        getContentPane().add(playersPanel, java.awt.BorderLayout.CENTER);

        controlsPanel.setBackground(new java.awt.Color(204, 204, 204));
        controlsPanel.setMinimumSize(new java.awt.Dimension(364, 20));
        controlsPanel.setPreferredSize(new java.awt.Dimension(100, 60));
        controlsPanel.setLayout(new java.awt.GridBagLayout());

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        controlsPanel.add(saveBtn, gridBagConstraints);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        controlsPanel.add(cancelBtn, gridBagConstraints);

        getContentPane().add(controlsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        gameCreator.newGame();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String[] players = {p1Field.getText(), 
                            p2Field.getText(), 
                            p3Field.getText(), 
                            p4Field.getText(), 
                            p5Field.getText(),
                            p6Field.getText(), 
                            p7Field.getText(), 
                            p8Field.getText(), 
                            p9Field.getText(), 
                            p10Field.getText()};
        gameCreator.savePlayers(players);
    }//GEN-LAST:event_saveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JTextField p10Field;
    private javax.swing.JLabel p10Label;
    private javax.swing.JTextField p1Field;
    private javax.swing.JLabel p1Label;
    private javax.swing.JTextField p2Field;
    private javax.swing.JLabel p2Label;
    private javax.swing.JTextField p3Field;
    private javax.swing.JLabel p3Label;
    private javax.swing.JTextField p4Field;
    private javax.swing.JLabel p4Label;
    private javax.swing.JTextField p5Field;
    private javax.swing.JLabel p5Label;
    private javax.swing.JTextField p6Field;
    private javax.swing.JLabel p6Label;
    private javax.swing.JTextField p7Field;
    private javax.swing.JLabel p7Label;
    private javax.swing.JTextField p8Field;
    private javax.swing.JLabel p8Label;
    private javax.swing.JTextField p9Field;
    private javax.swing.JLabel p9Label;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
// Credits: Roman Velic