/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package catchthebeat.ui;

import catchthebeat.GameCreator;
import catchthebeat.game.Score;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 * Class ScoreDialog
 * 
 * This JDialog shows highest 3 scores achieved in any game setting.
 * 
 * 1) If a game score is provided the class shows it (player's name & achieved
 *    number of beats) in its title otherwise shows "High Score"
 * 
 * The JDialog is created by and communicates with GameCreator.
 * 
 * @author Roman Velic
 * @version 2012.04
 */
public class ScoreDialog extends javax.swing.JDialog {

    private GameCreator gameCreator;
    /** Creates new form ScoreDialog */
    public ScoreDialog(java.awt.Frame parent, boolean modal, GameCreator gmc, ArrayList<Score> highScores, Score score) {
        super(parent, modal);
        initComponents();
        gameCreator = gmc;
        
        if (score != null) {
            this.setTitle(score.getWinner().getName() + " won the game with " + score.getPoints() + " beats!");
        } else {
            this.setTitle("High Score");
        }
        
        //set winner labels (max 3)
        JLabel[] winners = {firstPlayerLabel, secondPlayerLabel, thirdPlayerLabel};
        for (int i = 0; i < highScores.size() && i < winners.length; i++) {
            winners[i].setText(highScores.get(i).getWinner().getName() + " (" +
                               highScores.get(i).getPoints() + " beats)");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scorePanel = new javax.swing.JPanel();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        firstPlayerLabel = new javax.swing.JLabel();
        secondPlayerLabel = new javax.swing.JLabel();
        thirdPlayerLabel = new javax.swing.JLabel();
        controlsPanel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("High Score");
        setLocationByPlatform(true);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(430, 280));
        setResizable(false);

        scorePanel.setLayout(new java.awt.GridBagLayout());

        firstLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        firstLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstLabel.setText("1st:");
        firstLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        scorePanel.add(firstLabel, gridBagConstraints);

        secondLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        secondLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondLabel.setText("2nd:");
        secondLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        scorePanel.add(secondLabel, gridBagConstraints);

        thirdLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        thirdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        thirdLabel.setText("3rd:");
        thirdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        scorePanel.add(thirdLabel, gridBagConstraints);

        firstPlayerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        firstPlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPlayerLabel.setText("None");
        firstPlayerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        scorePanel.add(firstPlayerLabel, gridBagConstraints);

        secondPlayerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        secondPlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondPlayerLabel.setText("None");
        secondPlayerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        scorePanel.add(secondPlayerLabel, gridBagConstraints);

        thirdPlayerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        thirdPlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thirdPlayerLabel.setText("None");
        thirdPlayerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        scorePanel.add(thirdPlayerLabel, gridBagConstraints);

        getContentPane().add(scorePanel, java.awt.BorderLayout.CENTER);

        controlsPanel.setBackground(new java.awt.Color(204, 204, 204));
        controlsPanel.setPreferredSize(new java.awt.Dimension(95, 60));
        controlsPanel.setLayout(new java.awt.GridBagLayout());

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 15;
        controlsPanel.add(okBtn, gridBagConstraints);

        getContentPane().add(controlsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        gameCreator.newGame();
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel firstPlayerLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel secondPlayerLabel;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JLabel thirdPlayerLabel;
    // End of variables declaration//GEN-END:variables
}
// Credits: Roman Velic